name: kaliam
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Fonts
  google_fonts: ^4.0.3
  # Adt
  kalil_adt_annotation: ^3.0.10
  # Widgets
  material_widgets: ^0.4.0-preview.9
  # Utils
  kalil_utils: ^3.0.4
  # State management
  value_listenables: ^0.0.2-prerelease.20
  bloc: ^8.1.2
  # Vector drawable
  vector_drawable_path_utils:
    path: ../vector_drawable/packages/vector_drawable_path_utils
  vector_drawable_core:
    path: ../vector_drawable/packages/vector_drawable_core
  vector_drawable_style_extractor:
    path: ../vector_drawable/packages/vector_drawable_style_extractor
  vector_drawable_from_svg:
    path: ../vector_drawable/packages/vector_drawable_from_svg
  vector_drawable_annotation:
    path: ../vector_drawable/codegen_packages/vector_drawable_annotation
  vector_drawable:
    path: ../vector_drawable/flutter_packages/vector_drawable
  # Firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  cloud_functions: ^4.6.0
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.6.0

dependency_overrides:
  analyzer: ^5.2.0

dev_dependencies:
  # Build stuff 
  analyzer: ^5.2.0
  build_runner: ^2.3.3
  # Adt
  adt_generator: ^3.0.11
  # Vector drawable
  vector_drawable_code_generator:
    path: ../vector_drawable/codegen_packages/vector_drawable_code_generator
  # Flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true